import type { ActivityEntry, ItemView } from "./view"
import { HOUSE_OWNER } from "./view"

const cover = (seed: string) => `https://picsum.photos/seed/gk-${seed}/600/600`

export const items: ItemView[] = [
  {
    id: "a1f0c1",
    title: "Kind of Blue",
    artist: "Miles Davis",
    year: 1959,
    genre: "Jazz",
    label: "Columbia",
    format: 'Vinyl LP (12")',
    condition: "Very Good Plus",
    status: "playing",
    location: "Turntable — Counter",
    ownership: "house",
    ownerName: HOUSE_OWNER,
    addedAt: "2024-01-04",
    notes: "House favourite. Sleeve has a small split on the bottom edge.",
    cover: cover("kind-of-blue"),
  },
  {
    id: "b2e1d2",
    title: "Blue Train",
    artist: "John Coltrane",
    year: 1958,
    genre: "Jazz",
    label: "Blue Note",
    format: 'Vinyl LP (12")',
    condition: "Near Mint",
    status: "in-collection",
    location: "Shelf A1",
    ownership: "loan",
    ownerName: "John Carter",
    ownerContact: "john.carter@email.com",
    addedAt: "2024-01-15",
    notes: "Regular customer. Collects hard bop.",
    cover: cover("blue-train"),
  },
  {
    id: "c3d2e3",
    title: "A Love Supreme",
    artist: "John Coltrane",
    year: 1965,
    genre: "Jazz",
    label: "Impulse!",
    format: 'Vinyl LP (12")',
    condition: "Very Good",
    status: "in-collection",
    location: "Shelf A1",
    ownership: "loan",
    ownerName: "John Carter",
    ownerContact: "john.carter@email.com",
    addedAt: "2024-01-15",
    cover: cover("a-love-supreme"),
  },
  {
    id: "d4c3f4",
    title: "Rumours",
    artist: "Fleetwood Mac",
    year: 1977,
    genre: "Rock",
    label: "Warner Bros.",
    format: 'Vinyl LP (12")',
    condition: "Good",
    status: "on-loan",
    location: "Table 4",
    ownership: "loan",
    ownerName: "Maria Lopez",
    ownerContact: "maria.lopez@email.com",
    addedAt: "2024-02-03",
    notes: "Held for listening at table 4. Return by closing.",
    cover: cover("rumours"),
  },
  {
    id: "e5f4a5",
    title: "The Köln Concert",
    artist: "Keith Jarrett",
    year: 1975,
    genre: "Jazz",
    label: "ECM",
    format: 'Vinyl LP (12")',
    condition: "Very Good",
    status: "on-loan",
    location: "Table 2",
    ownership: "loan",
    ownerName: "Maria Lopez",
    ownerContact: "maria.lopez@email.com",
    addedAt: "2024-02-03",
    cover: cover("koln-concert"),
  },
  {
    id: "f6a5b6",
    title: "Blonde on Blonde",
    artist: "Bob Dylan",
    year: 1966,
    genre: "Folk Rock",
    label: "Columbia",
    format: 'Vinyl LP (12")',
    condition: "Good",
    status: "repair",
    location: "Repair bench",
    ownership: "donation",
    ownerName: "Downtown Vinyl Club",
    ownerContact: "contact@downtownvinylclub.com",
    addedAt: "2024-04-10",
    notes: "Sleeve torn at the spine. Owner aware and okay with the delay.",
    cover: cover("blonde-on-blonde"),
  },
  {
    id: "a7b6c7",
    title: "Voodoo",
    artist: "D'Angelo",
    year: 2000,
    genre: "Neo Soul",
    label: "Virgin",
    format: 'Vinyl LP (12")',
    condition: "Near Mint",
    status: "in-collection",
    location: "Shelf B2",
    ownership: "house",
    ownerName: HOUSE_OWNER,
    addedAt: "2023-11-18",
    cover: cover("voodoo"),
  },
  {
    id: "b8c7d8",
    title: "Selected Ambient Works 85–92",
    artist: "Aphex Twin",
    year: 1992,
    genre: "Electronic",
    label: "R&S Records",
    format: 'Vinyl LP (12")',
    condition: "Very Good Plus",
    status: "in-collection",
    location: "Shelf C1",
    ownership: "house",
    ownerName: HOUSE_OWNER,
    addedAt: "2023-12-02",
    cover: cover("saw-85-92"),
  },
  {
    id: "c9d8e9",
    title: "Songs in the Key of Life",
    artist: "Stevie Wonder",
    year: 1976,
    genre: "Soul",
    label: "Tamla",
    format: 'Vinyl LP (12")',
    condition: "Very Good",
    status: "in-collection",
    location: "Shelf B2",
    ownership: "donation",
    ownerName: "Elena Rossi Memorial Donation",
    ownerContact: "rossi.family@email.com",
    addedAt: "2024-03-01",
    notes: "Donated in memory of a regular. Handle with care.",
    cover: cover("key-of-life"),
  },
  {
    id: "d0e9f0",
    title: "Purple Rain",
    artist: "Prince and The Revolution",
    year: 1984,
    genre: "Pop",
    label: "Warner Bros.",
    format: 'Vinyl LP (12")',
    condition: "Very Good Plus",
    status: "in-collection",
    location: "Shelf B3",
    ownership: "house",
    ownerName: HOUSE_OWNER,
    addedAt: "2023-10-21",
    cover: cover("purple-rain"),
  },
  {
    id: "e1f0a1",
    title: "OK Computer",
    artist: "Radiohead",
    year: 1997,
    genre: "Alternative",
    label: "Parlophone",
    format: "CD",
    condition: "Near Mint",
    status: "in-collection",
    location: "Cabinet D — CD",
    ownership: "house",
    ownerName: HOUSE_OWNER,
    addedAt: "2023-09-14",
    cover: cover("ok-computer"),
  },
  {
    id: "f2a1b2",
    title: "Discovery",
    artist: "Daft Punk",
    year: 2001,
    genre: "Electronic",
    label: "Parlophone",
    format: "CD",
    condition: "Very Good",
    status: "in-collection",
    location: "Cabinet D — CD",
    ownership: "loan",
    ownerName: "Kevin Nguyen",
    ownerContact: "kevin.n@email.com",
    addedAt: "2024-03-20",
    cover: cover("discovery"),
  },
  {
    id: "a3b2c3",
    title: "Back to Black",
    artist: "Amy Winehouse",
    year: 2006,
    genre: "Soul",
    label: "Island",
    format: "CD",
    condition: "Good",
    status: "missing",
    location: "Unknown",
    ownership: "house",
    ownerName: HOUSE_OWNER,
    addedAt: "2023-08-05",
    notes: "Not found during the last shelf audit. Flagged for staff review.",
    cover: cover("back-to-black"),
  },
  {
    id: "b4c3d4",
    title: "Return to Forever",
    artist: "Chick Corea",
    year: 1972,
    genre: "Jazz Fusion",
    label: "ECM",
    format: 'Vinyl EP (7")',
    condition: "Very Good",
    status: "in-collection",
    location: "Shelf A4",
    ownership: "loan",
    ownerName: "John Carter",
    ownerContact: "john.carter@email.com",
    addedAt: "2024-01-15",
    cover: cover("return-to-forever"),
  },
  {
    id: "c5d4e5",
    title: "Untitled (Black on Black)",
    artist: "Kendrick Lamar",
    year: 2015,
    genre: "Hip Hop",
    label: "Aftermath",
    format: 'Vinyl LP (12")',
    condition: "Near Mint",
    status: "reclaimed",
    location: "N/A — picked up",
    ownership: "loan",
    ownerName: "Kevin Nguyen",
    ownerContact: "kevin.n@email.com",
    addedAt: "2024-03-20",
    notes: "Owner came back for it after two weeks. All good.",
    cover: cover("tpab"),
  },
  {
    id: "d6e5f6",
    title: "Bitches Brew",
    artist: "Miles Davis",
    year: 1970,
    genre: "Jazz Fusion",
    label: "Columbia",
    format: 'Vinyl LP (12")',
    condition: "Fair",
    status: "repair",
    location: "Repair bench",
    ownership: "house",
    ownerName: HOUSE_OWNER,
    addedAt: "2023-07-30",
    notes: "Warped from the window display. Attempting to flatten.",
    cover: cover("bitches-brew"),
  },
]

export const activity: ActivityEntry[] = [  {
    id: "act-1",
    itemId: "a1f0c1",
    itemTitle: "Kind of Blue",
    action: "Played for customer",
    staff: "bwilliams",
    note: "Requested by a table during the evening service.",
    createdAt: "2024-05-02T19:42:00",
  },
  {
    id: "act-2",
    itemId: "d4c3f4",
    itemTitle: "Rumours",
    action: "Lent to customer",
    staff: "asmith",
    note: "Held at table 4 until closing.",
    createdAt: "2024-05-02T18:15:00",
  },
  {
    id: "act-3",
    itemId: "a3b2c3",
    itemTitle: "Back to Black",
    action: "Marked missing",
    staff: "jdoe",
    note: "Not on the shelf during the monthly audit.",
    createdAt: "2024-05-01T11:03:00",
  },
  {
    id: "act-4",
    itemId: "f6a5b6",
    itemTitle: "Blonde on Blonde",
    action: "Condition updated",
    staff: "bwilliams",
    note: "Spine tear noted; moved to the repair bench.",
    createdAt: "2024-04-30T09:27:00",
  },
  {
    id: "act-5",
    itemId: "a1f0c1",
    itemTitle: "Kind of Blue",
    action: "Returned to shelf",
    staff: "asmith",
    note: "Back in rotation after the lunch service.",
    createdAt: "2024-04-29T15:50:00",
  },
  {
    id: "act-6",
    itemId: "b2e1d2",
    itemTitle: "Blue Train",
    action: "Checked in",
    staff: "jdoe",
    note: "Dropped off by John Carter.",
    createdAt: "2024-04-28T10:12:00",
  },
]

export interface DiscogsResult {
  id: number
  title: string
  artist: string
  year: number
  label: string
  genre: string
  format: 'Vinyl LP (12")' | 'Vinyl EP (7")' | "CD" | "Cassette"
  cover: string
}

// TODO(discogs): replace with the live Discogs search once DISCOGS_TOKEN is
// present in the environment. These mirror the shape returned by the API.
export const discogsResults: DiscogsResult[] = [
  {
    id: 1001,
    title: "In Rainbows",
    artist: "Radiohead",
    year: 2007,
    label: "XL Recordings",
    genre: "Alternative",
    format: 'Vinyl LP (12")',
    cover: cover("in-rainbows"),
  },
  {
    id: 1002,
    title: "The Miseducation of Lauryn Hill",
    artist: "Lauryn Hill",
    year: 1998,
    label: "Ruffhouse",
    genre: "Hip Hop",
    format: 'Vinyl LP (12")',
    cover: cover("miseducation"),
  },
  {
    id: 1003,
    title: "Ctrl",
    artist: "SZA",
    year: 2017,
    label: "Top Dawg",
    genre: "R&B",
    format: 'Vinyl EP (7")',
    cover: cover("ctrl"),
  },
  {
    id: 1004,
    title: "Cross",
    artist: "Justice",
    year: 2007,
    label: "Ed Banger",
    genre: "Electronic",
    format: "CD",
    cover: cover("cross"),
  },
  {
    id: 1005,
    title: "Tapestry",
    artist: "Carole King",
    year: 1971,
    label: "Ode Records",
    genre: "Singer-Songwriter",
    format: 'Vinyl LP (12")',
    cover: cover("tapestry"),
  },
  {
    id: 1006,
    title: "Blue Lines",
    artist: "Massive Attack",
    year: 1991,
    label: "Wild Bunch",
    genre: "Trip Hop",
    format: "Cassette",
    cover: cover("blue-lines"),
  },
]

